name: Build and release ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download firmware artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Delete existing latest release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: latest
        github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Generate build info
      id: build_info
      run: |
        echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
        echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

    - name: Create Latest Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Latest Firmware Build
        body: |
          🚀 **Latest ZMK Firmware Build**

          **Build Info:**
          - **Commit:** ${{ steps.build_info.outputs.short_sha }}
          - **Built:** ${{ steps.build_info.outputs.timestamp }}

          **Installation:**
          1. Put keyboard half in bootloader mode (double-tap reset)
          2. Drag and drop the .uf2 file to the mounted drive
          3. Repeat for the other half
        files: ./artifacts/**/*.uf2
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

